fix: error TS2339: Property 'VISUALIZE' does not exist on type 'typeof TargetLanguage' (backport #1293) (#1309)
# Backport

This will backport the following commits from `main` to
`maintenance/v5.2`:
- [fix: error TS2339: Property &#x27;VISUALIZE&#x27; does not exist on
type &#x27;typeof TargetLanguage&#x27;
(#1293)](https://github.com/aws/jsii-rosetta/pull/1293)

<!--- Backport version: 9.3.0 -->

### Questions ?
Please refer to the [Backport tool
documentation](https://github.com/sqren/backport)

Co-authored-by: Momo Kornher <kornherm@amazon.co.uk>